In [1]:
import time
import random
st=time.time()
x=[]
for i in range(500):
  y=[]
  for j in range(500):
    i=random.randint(0,256)
    y.append(i)
  x.append(y)
print(x)
et=time.time()
print(x)
print("Time taken to execute the code=",et-st)

[[191, 99, 242, 242, 121, 236, 163, 75, 191, 110, 152, 27, 235, 2, 29, 172, 12, 3, 143, 241, 70, 75, 47, 234, 53, 34, 127, 157, 179, 59, 140, 71, 24, 140, 62, 23, 67, 135, 146, 256, 10, 45, 216, 252, 3, 7, 75, 197, 88, 182, 169, 59, 54, 114, 161, 253, 210, 36, 165, 81, 49, 173, 179, 148, 69, 128, 137, 254, 39, 172, 245, 165, 162, 10, 25, 136, 130, 31, 114, 129, 134, 102, 131, 137, 15, 204, 89, 237, 237, 71, 92, 49, 215, 160, 116, 27, 221, 104, 72, 51, 113, 73, 219, 88, 1, 170, 74, 186, 113, 159, 74, 110, 128, 86, 114, 87, 150, 224, 172, 104, 93, 194, 142, 241, 184, 50, 213, 3, 211, 205, 54, 46, 124, 133, 109, 250, 202, 46, 145, 38, 179, 166, 175, 15, 252, 136, 135, 187, 144, 149, 180, 7, 8, 189, 132, 160, 119, 253, 80, 212, 232, 191, 55, 230, 64, 131, 211, 115, 179, 121, 99, 170, 34, 139, 179, 154, 176, 252, 67, 59, 35, 72, 125, 196, 136, 186, 127, 238, 219, 8, 16, 9, 223, 121, 59, 7, 201, 119, 143, 159, 194, 248, 119, 45, 179, 55, 33, 214, 211, 100, 192, 160, 127, 43, 185, 56, 43, 89,

In [2]:
import numpy as np

x1=np.array([1,2,3,4,5])
print(x1)
print(x1.shape)
print(x1.ndim)
print(x1.dtype)

[1 2 3 4 5]
(5,)
1
int64


In [3]:
x2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x2)
print(x2.shape)
print(x2.ndim)
print(x2.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
int64


In [4]:
import random
import time

st=time.time()
a=[]

for i in range(2160):
  b=[]
  for j in range(3840):
    i=random.randint(0,255)
    b.append(i)
  a.append(b)
print(a)
et=time.time()
print("Time take to execute the code=",et-st)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [5]:
import random
import time

st=time.time()
a=np.random.randint(0,255,(2160,3840))
print(a)
et=time.time()
print("Time take to execute the code=",et-st)

[[221 231 122 ...  89 170  71]
 [ 92 176  41 ...  96 191 212]
 [ 17 245  39 ... 120  13 245]
 ...
 [ 74 177 154 ... 165 254 171]
 [246  89 247 ... 213  58 179]
 [162  73 114 ...  77  25  50]]
Time take to execute the code= 0.09446954727172852


In [6]:
# Arithmetic Opration on 2d array
print(x2/2)

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]


In [7]:
# Create an array and initialize with 0
x4=np.zeros(10,dtype="int")
print(x4)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
# Create a 2d array and initialize with -5
x4=np.full((5,10),-5,dtype="int")
print(x4)

[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]]


In [9]:
# Create a 2d array of certain range and rows and columns
x3=np.random.randint(0,255,(5,10))
print(x3)

[[222  52 164  26  70 190 205  77 129 158]
 [214 218  59  15 199 162 140  66 116 233]
 [226 188 173  10  26 143 113 218  21 146]
 [ 95 204 118  36   7 133   4  51  76  59]
 [225 251 185  60  67 209  49 196 183  47]]


In [10]:
# Aggregation function in 2d array
print(x3[3,7])
print(x3[:,7])
print(x3.mean())
print(x3.sum())
print(x3.min())
print(x3.max())
print(x3.size)

51
[ 77  66 218  51 196]
124.68
6234
4
251
50


In [11]:
# Change element in a 2d array
x3[:,7]=0
print(x3)

[[222  52 164  26  70 190 205   0 129 158]
 [214 218  59  15 199 162 140   0 116 233]
 [226 188 173  10  26 143 113   0  21 146]
 [ 95 204 118  36   7 133   4   0  76  59]
 [225 251 185  60  67 209  49   0 183  47]]


In [12]:
# Create an array using arange
x5=np.arange(1,10,2,dtype=int)
print(x5)

[1 3 5 7 9]


In [13]:
# Get 20 numbers between 1 and 10
x6=np.linspace(1,10,20)
print(x6)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [14]:
# NPS Analysis

!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 11.8MB/s]


In [15]:
a=np.loadtxt("survey.txt")
print(a)

[ 7. 10.  5. ...  5.  9. 10.]


In [16]:
#size of promotoers and detractors
promoters=a[a>=9].size
print(promoters)

detractors=a[a<=6].size
print(detractors)

609
332


In [17]:
#percentage of promotoers and detractors and NPS Calculation
p_promoters= 100*promoters/a.size

p_detractors= 100*detractors/a.size

NPS= p_promoters-p_detractors
print(round(NPS,2))

23.74


In [18]:
# Changing shape of a 2d array
array=np.arange(1,100,10)
print(array)

arr=array.reshape((5,2))
print(arr)

[ 1 11 21 31 41 51 61 71 81 91]
[[ 1 11]
 [21 31]
 [41 51]
 [61 71]
 [81 91]]


In [42]:
# Masking
player=["Manoj","Pravallika","Akash","Manoj","Pravallika","Akash",
         "Manoj","Pravallika","Akash","Manoj","Pravallika","Akash"]

scores=[10,8,10,6,9,7,
          8,8,8,7,8,9]

p=np.array(player)
s=np.array(scores)

In [43]:
# Masking players and getting Manoj's score
mask=p=="Manoj"
print(mask)

print(p[mask])
print(s[mask])

[ True False False  True False False  True False False  True False False]
['Manoj' 'Manoj' 'Manoj' 'Manoj']
[10  6  8  7]


In [45]:
# Masking players and getting Akash's highest score
mask1=p=="Akash"
print(s[mask].max()) # OR
print(np.max(s[mask]))

print(np.mean(s[mask]))

10
10
7.75


In [55]:
# Changing negative numbers to Zero using Masking
t=np.random.randint(1,50,(3,5))
print(t)

[[21 48 26 21 21]
 [47 44 41  1 15]
 [39 25 34 21 37]]


In [56]:
t=t-20
print(t)

[[  1  28   6   1   1]
 [ 27  24  21 -19  -5]
 [ 19   5  14   1  17]]


In [59]:
mask2=t<0
t[mask2]=0
print(t)
# OR
# t[t<0]=0
# print(t)

[[ 1 28  6  1  1]
 [27 24 21  0  0]
 [19  5 14  1 17]]


In [61]:
# Transposing the array
print(t.T)

[[ 1 27 19]
 [28 24  5]
 [ 6 21 14]
 [ 1  0  1]
 [ 1  0 17]]


In [72]:
# Accessing Elements
l=np.arange(1,30,2).reshape(3,5)
print(l)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]


In [78]:
print(l[0:,2])
print(l[1:,3:])
print(l[:-1,:-1])

[ 5 15 25]
[[17 19]
 [27 29]]
[[ 1  3  5  7]
 [11 13 15 17]]


In [86]:
# Sorting
l1=np.random.randint(0,15,7)
print(l1)

[ 0 11 12 13  3  5  6]


In [89]:
print(np.sort(l1)[::-1])

[13 12 11  6  5  3  0]
